### PR TITLE
fix(lib,scripts): import locally for linting, snapshot tests, dev server

### LINKED ISSUE #1923: Lint library modules
### Is there an existing issue outlining your problem?

- [x] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

Library modules should be linted so that they do not contain errors that can break userstyles downstream.

### LINKED ISSUE #1949: Dev server for library modules
### Is there an existing issue outlining your problem?

- [x] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

I usually use `miniserve .` (https://github.com/svenstaro/miniserve) to serve the userstyles directory and use `@import "http://127.0.0.1:8080/lib/<lib>.less";` for local imports in my files. Would be good to either get this documented or have a command to do this through Deno for the user. Could also be something where we experiment with post-processing of userstyles by transforming `userstyles.catppuccin.com` links into local URLs and then serve them at `http://127.0.0.1:8080/styles/foo/catppuccin.user.less` for local usage/reloading.

### PR DESCRIPTION
**Pull request by uncenter**
- [x] Lint userstyles with local library version (by replacing userstyles.catppuccin.com/lib imports with local path imports). Closes #1923.
- [x] Snapshot testing for library functions.
- [x] Serve modified userstyles for dev work. Closes #1949.
- [ ] Document how to write libraries, how to work with them in development, etc.

### CODE REVIEW

File: scripts/lint/main.ts [hunk 1]
```diff
@@ -24,12 +24,19 @@ const stylesheets = userstyle
...
 let didLintFail = false;
+const patches = [
+  ["https://userstyles.catppuccin.com/lib", path.join(REPO_ROOT, "lib")],
+];
 
 for (const style of stylesheets) {
   const dir = path.basename(path.dirname(style));
   const file = path.relative(REPO_ROOT, style);
 
   let content = await Deno.readTextFile(style);
```
Comment (WalkQuackBack) [inline scripts/lint/main.ts:35]: Still not too sure about temporarily modifying the file system, but it works.

File: scripts/serve/main.ts [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+
+import * as path from "@std/path";
+
+import { REPO_ROOT } from "@/constants.ts";
+
+const args = parseArgs(Deno.args, { boolean: ["fix"] });
+const userstyle = args._[0]
+  ?.toString()
+  .match(
+    /(?<base>styles\/)?(?<userstyle>[a-z0-9_\-.]+)(?<trailing>\/)?(?<file>catppuccin\.user\.less)?/,
```
Comment (WalkQuackBack) [inline scripts/serve/main.ts:14]: Could this RegEx be documented?

File: scripts/serve/main.ts [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+  }
+
+  return hash.digest("hex");
+}
+
+let lastLibChecksum = await calculateLibChecksum();
+
+async function updateTempUserstyle() {
+  let contents = await Deno.readTextFile(userstylePath);
+
```
Comment (WalkQuackBack) [inline scripts/serve/main.ts]:
```suggestion
/* Appends a query parameter suffix to import URLs from userstyles.catppuccin.com, containing the library modules content checksum.  */
```
Didn't entirely understand what this did: a better comment would help

File: scripts/serve/main.ts [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+import { REPO_ROOT } from "@/constants.ts";
+
+const args = parseArgs(Deno.args, { boolean: ["fix"] });
+const userstyle = args._[0]
+  ?.toString()
+  .match(
+    /(?<base>styles\/)?(?<userstyle>[a-z0-9_\-.]+)(?<trailing>\/)?(?<file>catppuccin\.user\.less)?/,
+  )?.groups?.userstyle;
+if (!userstyle) throw new Error("Invalid userstyle argument");
```
Comment (WalkQuackBack) [inline scripts/serve/main.ts:16]:
```suggestion
if (!userstyle) throw new Error("Invalid userstyle argument: expected key from userstyles.yml");
```

Is this confusing?

File: scripts/serve/main.ts [hunk 5]
```diff
@@ -0,0 +1,110 @@
+import { parseArgs } from "@std/cli";
+import { serveDir } from "@std/http/file-server";
+import { debounce } from "@std/async/debounce";
+import { createHash } from "node:crypto";
+
+import * as path from "@std/path";
+
+import { REPO_ROOT } from "@/constants.ts";
+
+const args = parseArgs(Deno.args, { boolean: ["fix"] });
```
Comment (WalkQuackBack) [inline scripts/serve/main.ts]:
```suggestion
const args = parseArgs(Deno.args, {});
```

Is the fix boolean argument an unintentional carryover from lint?

File: scripts/tests/lib.test.ts [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+    ctx,
+    await compile(`
+.foo {
+  --bar: #lib.rgbify(red)[];
+}
+`),
+  );
+});
+
+// TODO: Add snapshot tests for library APIs.
```
Comment (WalkQuackBack) [inline scripts/tests/lib.test.ts]: Picking this up.

File: scripts/serve/main.ts (hunk 2 above)
Comment (uncenter) [reply scripts/serve/main.ts:14]: This is copy-pasted from our other scripts, it should be refactored into a general utility later but I would rather avoid that given #1698 changes first.

File: scripts/serve/main.ts (hunk 5 above)
Comment (uncenter) [reply scripts/serve/main.ts]: Yep, thanks!

File: scripts/lint/main.ts (hunk 1 above)
Comment (uncenter) [reply scripts/lint/main.ts:35]: How do you mean temporarily modifying the file system? Do you mean with applying the patches to the content and then undoing it in the variable here? I looked into mocking the userstyles.catppuccin.com URL for the Less importer but it is a pain in Deno - could be something to look into if/when we switch back to Node with MSW/Nock.

File: scripts/serve/main.ts (hunk 4 above)
Comment (uncenter) [reply scripts/serve/main.ts:16]: Could be worth improving this for sure, going to knock it back to a later PR when we refactor this into a utility function across the scripts.

File: scripts/lint/main.ts (hunk 1 above)
Comment (WalkQuackBack) [reply scripts/lint/main.ts:35]: Okay, we can leave it as is for now.

File: scripts/serve/main.ts [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+  const importRegex =
+    /(@import\s+"https:\/\/userstyles\.catppuccin\.com\/lib\/[^\s]+\.less")/g;
+  contents = contents.replace(importRegex, (match) => {
+    return match.replace(
+      /(\.less)/,
+      `$1?v=${lastLibChecksum.slice(0, 6)}`,
+    );
+  });
+
+  contents = contents.replaceAll(
```
Comment (uncenter) [inline scripts/serve/main.ts:86]:
```suggestion
  /* Then replace the remote userstyles.catppuccin.com host with the local(host) server URL for these imports. */
  contents = contents.replaceAll(
```

**Review by WalkQuackBack — DISMISSED** [review]

**Review by WalkQuackBack — COMMENTED** [review]
Should documentation of the testing apparatus come in this PR or later?

**Comment by WalkQuackBack** [comment]
It will be followed up in another PR.
